#!/bin/bash
url=$2
dfu_type=$1
serial=$3

mkdir tmp
cd tmp

aux_url=${url#*//}
aux_url=${aux_url%%/*}

openssl s_client -connect $aux_url:443 < /dev/null 2>/dev/null | openssl x509 -fingerprint -noout -in /dev/stdin > tmp
res=`cat tmp`
rm tmp
fp=${res#*=} 
fp=`echo $fp | tr ':' ' '`

echo $fp

JSON_STRING="{\"_topic\": \"/gateway/$serial/targetDfu\", \"rTopic\": \"/backend/g/$serial/targetDfu\", \"uuid\": \"09103290-1203901293-10293019239\", \"target\": \"gw_nrf51\", \"serial\": \"\", \"dfuType\": $dfu_type, \"message\": \"\", \"url\": \"$url\", \"fingerprint\": \"$fp\", \"md5\": \"\"}"

echo $JSON_STRING > tmp.json
cd ..

./cmd_send tmp/tmp.json $serial
