#!/bin/bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$parent_path"

TIMEOUT=$1 #seconds

input=`echo $@ | cut -c 6-`
input=`echo $input | xxd -r -p | base64`
input=`echo $input | sed 's/ //g'`


mqtt_id=$MQTT_SERVER_NAME
mqtt_gw_sn=$1

client_cert="../cert/*certificate.pem*"
client_key="../cert/*private.pem*"
server_cert="../cert/*root-CA*"
msg="123"

a=$(python3 write_read_gw_mqtt.py --mqtt_id $mqtt_id --broker a3apacvpactifn-ats.iot.sa-east-1.amazonaws.com --port 8883 --ssl SSL --ca_cert $server_cert --cli_cert $client_cert --cli_key $client_key --outtopic "gateway/$mqtt_gw_sn/version" --msg "$msg" --intopic "backend/g/$mqtt_gw_sn/version")
if [ ! -z "$a" ]
then
	ESP_version=`echo $a | jq -r '.stdout' | grep -oP '(?<=ESP: v)[^ ]*'`
	NRF_version=`echo $a | jq -r '.stdout' | grep -oP '(?<=NRF: )[^ ]*'`
	# sed -i "${n_lines}s/.*/$mqtt_gw_sn, $ESP_version, $NRF_version/" $file
	echo $ESP_version
	echo $NRF_version

fi


