name: Build and push to Github Packages

on:
  workflow_dispatch:
  push:
    branches: [ 'staging', 'main' ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/loopkeybr/lock-update-tool
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: 'linux/amd64'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            GITHUB_ACTOR=${{ secrets.ACTOR_GUSTAVO }}
            GITHUB_PASS=${{ secrets.PAT_GUSTAVO }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: 'linux/amd64'
